require("which-key").setup {
  preset = "modern",
  icons = {
    -- set to false to disable all mapping icons,
    -- both those explicitely added in a mapping
    -- and those from rules
    mappings = false,
  },
}

local wk = require("which-key")

-- Normal mappings with Prefix
wk.add({
    { "<leader>i", group = "+Ipython"},
    { "<leader>is", desc = "Start"},
    { "<leader>ir", desc = "RunAll"},
    { "<leader>it", desc = "RunAndTimeExec"},
    { "<leader>ic", desc = "ExecCell"},
    { "<leader>iC", desc = "ExecCellGoNext", mode = { "n", "v" }},
    { "<leader>il", desc = "ClearScreen"},
    { "<leader>ix", desc = "CloseFigure"},
    { "<leader>ih", desc = "ExecCurrentLine", mode = { "n", "v" }},
    { "<leader>i<space>", desc = "ExecCurrentLine", mode = { "n", "v" }},
    { "<leader>iR", desc = "Restart"},
    { "<leader>ij", desc = "NextCell"},
    { "<leader>ik", desc = "PrevCell"},
    { "<leader>c", group = "+Commenter"},
    { "<leader>cc", desc = "CommentLine"},
    { "<leader>ci", desc = "InvertComment"},
    { "<leader>cu", desc = "UncommentLine"},
    { "<leader>g", group = "+GitGutter"},
    { "<leader>gk", desc = "PrevHunk"},
    { "<leader>gj", desc = "NextHunk"},
    { "<leader>gh", desc = "GetLeftHunk"},
    { "<leader>gl", desc = "GetRightHunk"},
    { "<leader>gp", desc = "PreviewHunk"},
    { "<leader>gs", desc = "StageHunk"},
    { "<leader>gS", desc = "StageBuffer"},
    { "<leader>gu", desc = "UndoStageHunk"},
    { "<leader>gr", desc = "ResetHunk"},
    { "<leader>gR", desc = "ResetBuffer"},
    { "<leader>gd", desc = "DiffHunk"},
    { "<leader>gD", desc = "DiffBuffer"},
    { "<leader>gb", desc = "BlameLine"},
    { "<leader>gm", desc = "ThreeWayDiff"},
    { "<leader>gt", group = "+Toggle"},
    { "<leader>gtl", desc = "ToggleLineHL"},
    { "<leader>gtn", desc = "ToggleNumsHL"},
    { "<leader>gtb", desc = "ToggleBlame"},
    { "<leader>gts", desc = "ToggleSigns"},
    { "<leader>gtd", desc = "ToggleDeleted"},
    { "<leader>gtw", desc = "ToggleWordDiff"},
    { "<leader>gtt", desc = "ToggleLineHL+Deleted"},
    { "<leader>w", group = "+Vimwiki"},
    { "<leader>wc", desc = "ColorizeLine"},
    { "<leader>wi", desc = "DiaryIndex"},
    { "<leader>ws", desc = "UISelect"},
    { "<leader>wt", desc = "TabIndex"},
    { "<leader>ww", desc = "Index"},
    { "<leader>wd", desc = "DeleteFile"},
    { "<leader>wh", desc = "ToHTML"},
    { "<leader>whh", desc = "HTMLBrowse"},
    { "<leader>wn", desc = "Goto"},
    { "<leader>wr", desc = "RenameFile"},
    { "<leader>w<space>", group = "+Diary"},
    { "<leader>w<space>i", desc = "GenerateLinks"},
    { "<leader>w<space>t", desc = "TabMakeNote"},
    { "<leader>w<space>w", desc = "MakeNote"},
    { "<leader>w<space>y", desc = "MakeYesterdayDiaryNote"},
    { "<leader>w<space>m", desc = "MakeTomorrowDiaryNote"},
    { "<leader>f", group = "+Find" },
    { "<leader>ff", desc = "Files" },
    { "<leader>fb", desc = "Buffers" },
    { "<leader>fc", desc = "Commands" },
    { "<leader>fC", desc = "Config" },
    { "<leader>fh", desc = "Helptags" },
    { "<leader>fg", desc = "GFiles" },
    { "<leader>fm", desc = "Maps" },
    { "<leader>fr", desc = "Recent" },
    { "<leader>f;", desc = "CHistory" },
    { "<leader>fs", desc = "Snippets" },
    { "<leader>ft", desc = "HFiles" },
    { "<leader>fp", desc = "PFiles" },
    { "<leader>f`", desc = "Marks" },
    { "<leader>f.", desc = "Ag"},
    { "<leader>f/", desc = "BLines"},
    { "<leader>f?", desc = "Lines"},
    { "<leader>l", group = "+LSP"},
    { "<leader>lk", desc = "SignatureHelp"},
    { "<leader>ld", desc = "TypeDefinition"},
    { "<leader>le", desc = "ShowLineDiagnostics"},
    { "<leader>lE", desc = "ToggleDiagnostic"},
    { "<leader>lq", desc = "ListDiagnosticsLocation"},
    { "<leader>lr", desc = "Rename"},
    { "<leader>lf", desc = "Formatting"},
    { "<leader>lw", group = "+Workspace"},
    { "<leader>lwa", desc = "AddWorkspaceFolder"},
    { "<leader>lwr", desc = "RemoveWorkspaceFolder"},
    { "<leader>lwl", desc = "ListWorkspaceFolders"},
    { "<leader>lg", group = "+GoTo"},
    { "<leader>lgk", desc = "PrevDiagnostic"},
    { "<leader>lgj", desc = "NextDiagnostic"},
    { "<leader>s", group = "+Session"},
    { "<leader>sc", ":SClose<CR>", desc = "CloseSession"},
    { "<leader>sd", ":SDelete<CR>", desc = "DeleteSession"},
    { "<leader>sl", ":SLoad<CR>", desc = "LoadSession"},
    { "<leader>ss", ":Startify<CR>", desc = "StartPage"},
    { "<leader>sS", ":SSave<CR>", desc = "SaveSession"},
    { "<leader>so", ":Obsession<CR>", desc = "TrackSession"},
    { "<leader>sO", ":Obsession!<CR>", desc = "StopTrackSession"},
    { "<leader>a", group = "+Actions"},
    { "<leader>ac", ":ColorizerToggle<CR>", desc = "Colorizer"},
    { "<leader>ah", ":nohl<CR>", desc = "NoHighlight"},
    { "<leader><space>", desc = "EasyMotion"},
    { "<leader><CR>", desc = "SourceConfig"},
    { "<leader>j", desc = "NewlineBelow"},
    { "<leader>k", desc = "NewlineAbove"},
    { "<leader>t", group = "+Tab"},
    { "<leader>th", desc = "TabLeft"},
    { "<leader>tl", desc = "TabRight"},
    { "<leader>tH", desc = "TabFirst"},
    { "<leader>tL", desc = "TabLast"},
    { "<leader>tj", desc = "TabMoveLeft"},
    { "<leader>tk", desc = "TabMoveRight"},
    { "<leader>tc", desc = "TabClose"},
    { "<leader>tn", desc = "TabNew"},
    { "<leader>tr", desc = "TabRename"},
    { "<leader>d", group = "+DAP"},
    { "<leader>db", desc = "Breakpoint"},
    { "<leader>dB", desc = "ConditionalBreakpoint"},
    { "<leader>dE", desc = "ExceptionBreakpoint"},
    { "<leader>dh", desc = "StepOut"},
    { "<leader>dl", desc = "StepInto"},
    { "<leader>dj", desc = "StepBack"},
    { "<leader>dk", desc = "StepOver"},
    { "<leader>dd", desc = "Continue"},
    { "<leader>dc", desc = "ClearAllBreakpoints"},
    { "<leader>dC", desc = "RunToCursor"},
    { "<leader>dq", desc = "Quit"},
    { "<leader>dK", desc = "Up"},
    { "<leader>dJ", desc = "Down"},
    { "<leader>de", desc = "Evaluate"},
    { "<leader>du", desc = "ToggleUI"},
    { "<leader>di", group = "+Info"},
    { "<leader>dii", desc = "Interactive"},
    { "<leader>dib", desc = "Breakpoint"},
    { "<leader>dir", desc = "REPL"},
    { "<leader>dis", desc = "Scope"},
    { "<leader>dit", desc = "Stack"},
    { "<leader>diw", desc = "Watch"}
})

-- Normal mappings without Prefix
wk.add({
    { "cr", group = "AbolisCoercion" },
    { "cr-", desc = "dash-case" },
    { "cr.", desc = "dot.case" },
    { "cr<space>", desc = "space case" },
    { "crc", desc = "camelCase" },
    { "crm", desc = "MixedCase" },
    { "crs", desc = "snake_case" },
    { "crt", desc = "Title Case" },
    { "cru", desc = "UPPER_CASE" },
})

